{
  "stylesheets" : {
    "default" : [
      "bootstrap.min.css",
      "style.css"
    ],
   
    "widgets" : {
      "google_prettify" : "twitter-bootstrap.css"
    }
    
  },

  "javascripts" : {
    "default" : [
    ]
  },
  
  "manifest" : {
    "author" : "Daniel Guilak, Jacob Thornton and Mark Otto",
    "website" : "http://twitter.github.com/bootstrap"
  }
}
